name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.21"

      - run: bun install --frozen-lockfile

      - run: bun run build --filter='!@weaver-conf/demo'

      - name: Typecheck
        run: bun run typecheck --filter='!@weaver-conf/demo'

      - run: bun run lint --filter='!@weaver-conf/demo'

      - run: bun run test --filter='!@weaver-conf/demo'
